import Head from 'next/head'

import { LatestTweet, Grid, Card } from '../components'

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Guilherme Leite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <img src="/logo.png" width="240px" height="186px" />
        <p>Juntos pelos Sintrenses</p>
        <LatestTweet />
        <Grid>
          <Card
            title="Candidatos"
            description="Estamos a organizar uma lista plural de sintrenses"
            link="/brevemente"
          />
          <Card
            title="Objectivos"
            description="Devolver Sintra aos sintrenses e tornar o concelho um bom local para viver"
            link="/brevemente"
          />
          <Card
            title="Videos"
            description="Ajude a partilhar os vídeos desta lista"
            link="/brevemente"
          />
          <Card
            title="Comunicados"
            description="Ajude a partilhar a nossa comunicação"
            link="/brevemente"
          />
          <Card
            title="Agenda"
            description="Participe nos nossos eventos online"
            link="/brevemente"
          />
          <Card
            title="Mediakit"
            description="Este material é para os nossos apoiantes partilharem"
            link="/brevemente"
          />
        </Grid>
        <br />
        <br />
      </main>
    </div>
  )
}
