name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: |
        npm install
        npm run build
        touch out/.nojekyll
        echo "guilhermeleite.pt" > out/CNAME
    - uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: out/
        GH_PAT: ${{ secrets.GH_PAT }}